### ISSUE TITLE
Why are you creating that?

### ISSUE THREAD

**Issue by lemanschik** [holepunchto/tiny-paths#1]
Normaly new URL should give you all kind of path utils i only ask to keep track.

**Comment by LuKks** [comment]
It's a module replacement for the native module `path` of Node.js. And this is for file and directory paths

**Comment by lemanschik** [comment]
@LuKks but ECMAScript moves away from path import as also new URL got relativ to as option to solve all path issues simple use always file:// protocol there exists also a unified path now for windows that is all outdated to use path in general

**Comment by lemanschik** [comment]
@LuKks for example in nodejs most users are now adviced to do this for extension checks
```js
`be/path/with.filext`.endsWith('.filext') // true
`be/path/with.filext`.split('.').slice(-1) // 'filext'
new URL('foo', 'file:bar/').pathname // '/bar/foo'
new URL('foo', 'file:bar/').pathname.replaceAll('/','\') // '\bar\foo' not needed windows 10 is posix compatible.
```

**Comment by mafintosh** [comment]
Like @LuKks said , its a drop in replacement for nodejs’ path module for when that’s needed
